file(COPY ${CMAKE_CURRENT_SOURCE_DIR}/test DESTINATION ${CMAKE_CURRENT_BINARY_DIR})
file(COPY ${CMAKE_CURRENT_BINARY_DIR}/npm/bitprofile-contract DESTINATION ${CMAKE_CURRENT_BINARY_DIR}/test/node_modules)
